### ISSUE TITLE
Jenkins fails to start after upgrading to v1.0.1

### ISSUE THREAD

**Issue by Jakub-CZ** [jenkinsci/depgraph-view-plugin#23]
Hello,

this is similar to the previous issue.

Could it be because there is no `WEB-INF/classes` in depgraph-view.jpi?

Running from: /data/jenkins/jenkins.war
2020-02-16 19:49:01.063+0000 [id=1]	WARNING	winstone.Logger#logInternal: Parameter handlerCountMax is now deprecated
2020-02-16 19:49:01.077+0000 [id=1]	WARNING	winstone.Logger#logInternal: Parameter handlerCountMaxIdle is now deprecated
2020-02-16 19:49:01.083+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @5607ms to org.eclipse.jetty.util.log.JavaUtilLog
2020-02-16 19:49:01.180+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
2020-02-16 19:49:01.274+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.25.v20191220; built: 2019-12-20T17:00:00.294Z; git: a9729c7e7f33a459d2616a8f9e9ba8a90f432e95; jvm 1.8.0_65-b17
2020-02-16 19:49:01.985+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /jenkins, did not find org.eclipse.jetty.jsp.JettyJspServlet
2020-02-16 19:49:02.075+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2020-02-16 19:49:02.075+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2020-02-16 19:49:02.077+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 600000ms
2020-02-16 19:49:03.470+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /data/jenkins found at: SystemProperties.getProperty("JENKINS_HOME")
2020-02-16 19:49:03.657+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@20bd8be5{Jenkins v2.220,/jenkins,file:///var/cache/jenkins/war/,AVAILABLE}{/var/cache/jenkins/war}
2020-02-16 19:49:03.668+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@2ef9b8bc{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2020-02-16 19:49:03.668+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @8193ms
2020-02-16 19:49:03.668+0000 [id=18]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2020-02-16 19:49:49.579+0000 [id=34]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2020-02-16 19:49:51.600+0000 [id=34]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2020-02-16 19:49:57.517+0000 [id=36]	INFO	c.b.j.cascade.PluginActivator#start: ### Start.
2020-02-16 19:49:57.693+0000 [id=35]	INFO	c.n.jenkins.RepositoryPlugin#start: Expanding /data/jenkins/plugins/repository/WEB-INF/lib/repository.jarinto /data/jenkins/repositoryPlugin
2020-02-16 19:50:13.444+0000 [id=34]	WARNING	hudson.ExtensionFinder$Sezpoz#scout: Failed to scout com.barchart.jenkins.cascade.GraphProjectActionFatory
java.lang.ClassNotFoundException: hudson.plugins.depgraph_view.DependencyGraphProjectActionFactory
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Caused: java.lang.NoClassDefFoundError: hudson/plugins/depgraph_view/DependencyGraphProjectActionFactory
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1155)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:712)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1377)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:81)
	at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:2040)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
Caused: java.lang.InstantiationException
	at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
	at hudson.ExtensionFinder.getClassFromIndex(ExtensionFinder.java:751)
	at hudson.ExtensionFinder.access$900(ExtensionFinder.java:90)
	at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:736)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:338)
	at hudson.ExtensionList.load(ExtensionList.java:381)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
	at hudson.ExtensionList.getComponents(ExtensionList.java:183)
	at jenkins.model.Jenkins$6.onInitMilestoneAttained(Jenkins.java:1159)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:83)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.lambda$onAttained$3(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.run(ReactorListener.java:109)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:177)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2020-02-16 19:50:19.160+0000 [id=34]	WARNING	hudson.ExtensionFinder$Sezpoz#_find: Failed to load com.barchart.jenkins.cascade.GraphProjectActionFatory
java.lang.ClassNotFoundException: hudson.plugins.depgraph_view.DependencyGraphProjectActionFactory
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Caused: java.lang.NoClassDefFoundError: hudson/plugins/depgraph_view/DependencyGraphProjectActionFactory
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1155)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:712)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1377)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:81)
	at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:2040)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
Caused: java.lang.InstantiationException
	at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
	at hudson.ExtensionFinder.getClassFromIndex(ExtensionFinder.java:751)
	at hudson.ExtensionFinder.access$900(ExtensionFinder.java:90)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:711)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:700)
	at hudson.ExtensionFinder$GuiceFinder.refreshExtensionAnnotations(ExtensionFinder.java:303)
	at hudson.ExtensionFinder$GuiceFinder.<init>(ExtensionFinder.java:265)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:714)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:700)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:344)
	at hudson.ExtensionList.load(ExtensionList.java:381)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
	at hudson.ExtensionList.getComponents(ExtensionList.java:183)
	at jenkins.model.Jenkins$6.onInitMilestoneAttained(Jenkins.java:1159)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:83)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.lambda$onAttained$3(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.run(ReactorListener.java:109)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:177)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2020-02-16 19:50:20.044+0000 [id=34]	WARNING	hudson.ExtensionFinder$Sezpoz#_find: Failed to load com.barchart.jenkins.cascade.GraphProjectActionFatory
java.lang.ClassNotFoundException: hudson.plugins.depgraph_view.DependencyGraphProjectActionFactory
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Caused: java.lang.NoClassDefFoundError: hudson/plugins/depgraph_view/DependencyGraphProjectActionFactory
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1155)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:712)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1377)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:81)
	at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:2040)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
Caused: java.lang.InstantiationException
	at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
	at hudson.ExtensionFinder.getClassFromIndex(ExtensionFinder.java:751)
	at hudson.ExtensionFinder.access$900(ExtensionFinder.java:90)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:711)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:700)
	at hudson.ExtensionFinder$GuiceFinder.<init>(ExtensionFinder.java:280)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:714)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:700)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:344)
	at hudson.ExtensionList.load(ExtensionList.java:381)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
	at hudson.ExtensionList.getComponents(ExtensionList.java:183)
	at jenkins.model.Jenkins$6.onInitMilestoneAttained(Jenkins.java:1159)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:83)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.lambda$onAttained$3(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.run(ReactorListener.java:109)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:177)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2020-02-16 19:50:24.978+0000 [id=34]	WARNING	h.ExtensionFinder$GuiceFinder$SezpozModule#configure: Failed to load com.barchart.jenkins.cascade.GraphProjectActionFatory
java.lang.ClassNotFoundException: hudson.plugins.depgraph_view.DependencyGraphProjectActionFactory
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Caused: java.lang.NoClassDefFoundError: hudson/plugins/depgraph_view/DependencyGraphProjectActionFactory
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1155)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:712)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1377)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:81)
	at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:2040)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
Caused: java.lang.InstantiationException
	at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:529)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at hudson.ExtensionFinder$GuiceFinder.<init>(ExtensionFinder.java:285)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:714)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:700)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:344)
	at hudson.ExtensionList.load(ExtensionList.java:381)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
	at hudson.ExtensionList.getComponents(ExtensionList.java:183)
	at jenkins.model.Jenkins$6.onInitMilestoneAttained(Jenkins.java:1159)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:83)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.lambda$onAttained$3(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.run(ReactorListener.java:109)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:177)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2020-02-16 19:50:25.813+0000 [id=34]	INFO	c.b.jenkins.cascade.GraphModule#configure: ### GraphModule
2020-02-16 19:50:25.818+0000 [id=34]	SEVERE	h.ExtensionFinder$GuiceFinder#<init>: Failed to create Guice container from all the plugins
java.lang.ClassNotFoundException: hudson.plugins.depgraph_view.model.graph.EdgeProvider
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Caused: java.lang.NoClassDefFoundError: hudson/plugins/depgraph_view/model/graph/EdgeProvider
	at com.barchart.jenkins.cascade.GraphModule.configure(GraphModule.java:39)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at hudson.ExtensionFinder$GuiceFinder.<init>(ExtensionFinder.java:285)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:714)
	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:700)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:344)
	at hudson.ExtensionList.load(ExtensionList.java:381)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
	at hudson.ExtensionList.getComponents(ExtensionList.java:183)
	at jenkins.model.Jenkins$6.onInitMilestoneAttained(Jenkins.java:1159)
	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:83)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.lambda$onAttained$3(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.run(ReactorListener.java:109)
	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:102)
	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:177)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2020-02-16 19:50:29.178+0000 [id=34]	WARNING	hudson.ExtensionFinder$Sezpoz#_find: Failed to load hudson.ExtensionFinder$GuiceFinder
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Could not find a suitable constructor in jenkins.model.Jenkins. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at jenkins.model.Jenkins.class(Jenkins.java:315)
  while locating jenkins.model.Jenkins
    for field at jenkins.model.Jenkins$EnforceSlaveAgentPortAdministrativeMonitor.j(Jenkins.java:1319)
  at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:538)

2) Could not find a suitable constructor in jenkins.model.Jenkins. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at jenkins.model.Jenkins.class(Jenkins.java:315)
  while locating jenkins.model.Jenkins
    for field at jenkins.security.s2m.AdminCallableMonitor.jenkins(AdminCallableMonitor.java:33)
  at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:538)

3) Could not find a suitable constructor in jenkins.model.Jenkins. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at jenkins.model.Jenkins.class(Jenkins.java:315)
  while locating jenkins.model.Jenkins
    for field at jenkins.security.s2m.MasterKillSwitchConfiguration.jenkins(MasterKillSwitchConfiguration.java:20)
  at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:538)

3 errors
...
...

**Comment by guidograzioli** [comment]
Thanks for reporting. Unfortunately, your problem resides in the maven-release-cascade-plugin (repo here: https://github.com/jenkinsci/maven-release-cascade-plugin/blob/master/pom.xml ), which has not being updated for a few years, as the class it is looking for has been deleted from the depgraph-plugin back in 2010... (commit: https://github.com/jenkinsci/depgraph-view-plugin/commit/6a0299c4ab1a0a575f87e43a60ada5bc75a0d063#diff-4cab3ca33757398f362a9021b8b3bc43 )
Your choices are creating an issue against that plugin and wait for a PR, or/and downgrade depgraph-plugin back to version 0.11, which is the last one to have the required class.

**Comment by Jakub-CZ** [comment]
Hi,

I think I don't need Maven Cascade Release anymore. So I uninstalled it and now I can update depgraph.

Thanks.

**Comment by anushkagarg** [comment]
I'm also facing the same issue. Can you please tell how you uninstalled it.

**Comment by niyomi** [comment]
> Thanks for reporting. Unfortunately, your problem resides in the maven-release-cascade-plugin (repo here: https://github.com/jenkinsci/maven-release-cascade-plugin/blob/master/pom.xml ), which has not being updated for a few years, as the class it is looking for has been deleted from the depgraph-plugin back in 2010... (commit: [6a0299c#diff-4cab3ca33757398f362a9021b8b3bc43](https://github.com/jenkinsci/depgraph-view-plugin/commit/6a0299c4ab1a0a575f87e43a60ada5bc75a0d063#diff-4cab3ca33757398f362a9021b8b3bc43) )
> Your choices are creating an issue against that plugin and wait for a PR, or/and downgrade depgraph-plugin back to version 0.11, which is the last one to have the required class.

how can i downgrade depgraph please help

**Comment by guidograzioli** [comment]
To downgrade, you need to navigate to JENKINS_HOME/plugins directory, replace the depgraph.hpi file and directory with the depgraph.hpi.bak version. To uninstall the maven-release-cascade-plugin which is currently unmaintained, just delete the corresponding directory.

**Comment by guidograzioli** [comment]
JENKINS-62797
