### ISSUE TITLE
NPE in version 1.0.4

### ISSUE THREAD

**Issue by ejschoen** [jenkinsci/depgraph-view-plugin#29]
The dependency viewer was working until I added a specific new pipeline item to a cluster of pipeline items that are connected via some common libraries.  Now any attempt to see the dependency graph for that cluster of related items fails on a null pointer exception.  If you have suggestions for debugging, I can try to get you more information.  

```
Jul 30, 2020 6:46:30 PM WARNING hudson.init.impl.InstallUncaughtExceptionHandler handleException
Caught unhandled exception with ID 69872983-bf56-4392-92ce-8d9f801cea4c
java.lang.NullPointerException
	at hudson.plugins.depgraph_view.model.graph.edge.BuildTriggerEdgeProvider.getDownstreamEdgesIncidentWith(BuildTriggerEdgeProvider.java:80)
	at hudson.plugins.depgraph_view.model.graph.GraphCalculator.extendGraph(GraphCalculator.java:69)
	at hudson.plugins.depgraph_view.model.graph.GraphCalculator.generateGraph(GraphCalculator.java:58)
	at hudson.plugins.depgraph_view.AbstractDependencyGraphAction.doDynamic(AbstractDependencyGraphAction.java:129)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:480)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
```

**Comment by guidograzioli** [comment]
Thanks for reporting, it is definitely a bug; it seems due to the fact the there was no recent successful build for at least one of the pipelines in the cluster: I'll start working on a workaround, in the meanwhile I'd really appreciate if you can check whether my guess is true

**Comment by ejschoen** [comment]
Yes, indeed.  Once I managed to get a successful build, the error went away.
